"""Add process_management to App

Revision ID: 10409d74aa58
Revises: 684e3e9b62a4
Create Date: 2026-01-30 14:48:06.241837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10409d74aa58'
down_revision: Union[str, Sequence[str], None] = '684e3e9b62a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('process_management', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'process_management')
    # ### end Alembic commands ###
